"""Strike the `ornament` attribute onto a drawn page.

    from ornament import stamp
    image, report = stamp(image, recipe, boxes, seed=seed)

**This is the half of `ornament` that was missing.** The attribute has been in
the rule base since the beginning: 21 values in `rulebase/rules/ornament.yaml`,
27 PNGs in `textures/ornament/` generated by `tools/make_ornaments.py`, and
`pipeline/preflight.py` checks -- both ways -- that every value names a file and
every file is named by a value. All of it was true and none of it reached a
page: no renderer read `ornament.params.marks`, so every dataset this repository
has ever shipped recorded a seal in `synthesis.json` and printed no seal.

That is the exact failure `tools/rules_report.py --check` exists to catch one
level down ("a model no chain names is a model that has never been in a
dataset"), and the attribute walked past it because it is not a degradation
chain -- nothing was checking the second half of the sentence.

## Where a mark goes: the anchor

The rules name the place semantically -- `signature_seller`, `letterhead`,
`footer_band`, `table_back`, `page_full` -- because that is how a person
describes where a stamp lands, and because a fraction of the page height means
different things on a till roll and on an A4 form. `anchor()` resolves those
against the page's own boxes, which the HTML renderer has just measured from the
laid-out DOM:

    signature_seller   the `sign.` boxes, RIGHT-hand cluster when there are two
                       -- a Vietnamese invoice puts bên bán on the right
    letterhead         the `store.` boxes
    footer_band        the `footer` boxes
    table_back         the item table: `menu.`, `colhdr`, `colnum`, `cell`
    page_full          the whole sheet

A layout with no such block -- a till roll has no signature -- falls back to a
geometric region rather than dropping the mark, and the report says which of the
two happened. Both are recorded per page, so "the seal is in the wrong place on
this layout" is answerable from the metadata instead of by eye.

## Size, and why the anchor does not set it

`scale` stays a fraction of the PAGE width, exactly as the rules already mean
it (`0.26` for a company seal, `1.0` for a full-page watermark). The anchor
decides only WHERE the centre goes. A seal scaled to the signature block would
be a different size on every layout, and the rules were written against a page.

## The mark carries no label

Deliberate, and the same rule the signature ink is under: `boxes` are not
touched here. A seal is ink on the paper, not a field of the document -- a label
claiming text under a seal is what `pipeline/invariants.py` is built to catch,
and inventing a box for the seal itself would teach a detector to read a stamp
as a field.
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Any, Iterable, Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]
ORNAMENT_DIR = REPO_ROOT / "textures" / "ornament"

# kind prefixes that make up each semantic anchor, and the fraction of the page
# to fall back to when a layout has none of them: (x0, y0, x1, y1), relative.
#
# The fallbacks are where the mark would go on a page that HAS the block --
# a signature is bottom-right, a letterhead is the top strip -- so a till roll
# with no signature block still gets its seal somewhere a seal belongs.
# A purely geometric anchor -- a band, an edge, a corner -- names no prefix and
# always uses its rectangle: a ribbon across the top of the page is a place on
# the paper, not a block of the document, and there is nothing to measure.
ANCHORS: dict[str, tuple[tuple[str, ...], tuple[float, float, float, float]]] = {
    "signature_seller": (("sign.",), (0.55, 0.72, 0.95, 0.95)),
    "letterhead": (("store.",), (0.05, 0.02, 0.95, 0.18)),
    "footer_band": (("footer",), (0.05, 0.84, 0.95, 0.98)),
    "table_back": (("menu.", "colhdr", "colnum", "cell"), (0.08, 0.30, 0.92, 0.70)),
    "totals": (("total.",), (0.45, 0.62, 0.95, 0.82)),
    "page_full": ((), (0.0, 0.0, 1.0, 1.0)),
    "page_center": ((), (0.20, 0.30, 0.80, 0.70)),
    "header_band": ((), (0.0, 0.0, 1.0, 0.10)),
    "page_edge_left": ((), (0.0, 0.15, 0.09, 0.85)),
    "corner_tr": ((), (0.80, 0.02, 0.98, 0.16)),
    "corner_br": ((), (0.80, 0.84, 0.98, 0.98)),
    "corner_bl": ((), (0.02, 0.84, 0.20, 0.98)),
}

# Anchor used when a rule names one this file does not know. Never silently:
# `problems()` reports it, and preflight fails the run.
FALLBACK_ANCHOR = "page_full"


def _rect(quad) -> tuple[float, float, float, float]:
    xs = [point[0] for point in quad]
    ys = [point[1] for point in quad]
    return min(xs), min(ys), max(xs), max(ys)


def _hull(rects: Iterable[tuple[float, float, float, float]]):
    rects = list(rects)
    if not rects:
        return None
    return (min(r[0] for r in rects), min(r[1] for r in rects),
            max(r[2] for r in rects), max(r[3] for r in rects))


def _right_cluster(rects: list[tuple[float, float, float, float]]):
    """The right-hand half of a signature strip, when there are two blocks.

    A Vietnamese invoice signs in two columns -- người mua bên trái, người bán
    bên phải -- and the seal belongs to the seller. Split at the midpoint of the
    strip's own extent rather than the page's: a form whose two blocks both sit
    left of centre still has a left one and a right one.
    """
    if not rects:
        return None
    hull = _hull(rects)
    middle = (hull[0] + hull[2]) / 2
    right = [r for r in rects if (r[0] + r[2]) / 2 >= middle]
    return _hull(right or rects)


def anchor(name: str, boxes: Sequence[dict], width: int, height: int):
    """`(x0, y0, x1, y1, how)` in pixels. `how` is "boxes" or "fallback"."""
    prefixes, share = ANCHORS.get(name, ANCHORS[FALLBACK_ANCHOR])
    found: list[tuple[float, float, float, float]] = []
    if prefixes:
        for box in boxes:
            kind = str(box.get("kind") or "")
            if any(kind == p or kind.startswith(p) for p in prefixes):
                found.append(_rect(box["quad"]))
    hull = _right_cluster(found) if name == "signature_seller" else _hull(found)
    if hull is not None:
        return (*hull, "boxes")
    x0, y0, x1, y1 = share
    return (x0 * width, y0 * height, x1 * width, y1 * height, "fallback")


def _overlap(rect, boxes: Sequence[dict]) -> float:
    """Area of `rect` covered by labelled runs. Zero is clear paper."""
    x0, y0, x1, y1 = rect
    total = 0.0
    for box in boxes:
        quad = box.get("quad")
        if not quad:
            continue
        bx0, by0, bx1, by1 = _rect(quad)
        wide = min(x1, bx1) - max(x0, bx0)
        tall = min(y1, by1) - max(y0, by0)
        if wide > 0 and tall > 0:
            total += wide * tall
    return total


def clearest(rect, boxes: Sequence[dict], size: tuple[float, float],
             steps: int = 5, page: tuple[int, int] | None = None):
    """Where inside `rect` a mark of `size` covers the least text.

    A mark is composited by multiplying, so ordinary ink under a seal still
    reads through it -- that is the design and it holds for a seal. It does not
    hold for a QR code, which is half solid black by construction: multiplied
    over a title, the title is gone while the label still says every word of it
    is there. Measured on `insurance_property_contract`, whose `letterhead`
    anchor resolves to the hull of the party names in the middle of the page
    and dropped the verification QR straight over `HỢP ĐỒNG BẢO HIỂM TÀI SẢN`.

    So the mark is placed rather than centred: candidate positions on a coarse
    grid inside the anchor, scored by how much labelled text each would cover,
    and the emptiest wins. Coarse on purpose -- this runs per mark per page, and
    the difference between the best spot and the fifth-best is not worth a
    search. Ties keep the centre, which is where a stamp belongs when the whole
    anchor is equally busy.
    """
    x0, y0, x1, y1 = rect
    mark_w, mark_h = size
    room_x, room_y = (x1 - x0) - mark_w, (y1 - y0) - mark_h
    centre = ((x0 + x1 - mark_w) / 2, (y0 + y1 - mark_h) / 2)
    if room_x <= 1 and room_y <= 1:
        return (*centre, centre[0] + mark_w, centre[1] + mark_h)

    def search(rect):
        rx0, ry0, rx1, ry1 = rect
        rx, ry = (rx1 - rx0) - mark_w, (ry1 - ry0) - mark_h
        found, score_of = None, None
        for row in range(steps):
            for col in range(steps):
                px = rx0 + (rx * col / (steps - 1) if rx > 0 and steps > 1 else 0)
                py = ry0 + (ry * row / (steps - 1) if ry > 0 and steps > 1 else 0)
                here = (px, py, px + mark_w, py + mark_h)
                # Distance from the anchor's centre breaks ties, so a clear
                # anchor still stamps where a person would stamp.
                tie = abs(px - centre[0]) + abs(py - centre[1])
                score = (_overlap(here, boxes), tie)
                if score_of is None or score < score_of:
                    found, score_of = here, score
        return found, score_of

    best, best_score = search(rect)
    # A letterhead anchor is the hull of the store block, and on a dense form
    # every position inside it is on text -- searching there can only pick the
    # least bad. When that is still most of the mark, widen to the page band at
    # the anchor's own height: the margins beside a letterhead are where a real
    # QR goes anyway, and it is the difference between less overlap and none.
    if best_score and best_score[0] > 0.15 * mark_w * mark_h and page is not None:
        page_w, page_h = page
        band = (0.0, max(0.0, y0 - mark_h * 0.5),
                float(page_w), min(float(page_h), y1 + mark_h * 0.5))
        wider, wider_score = search(band)
        if wider_score and wider_score[0] < best_score[0]:
            best, best_score = wider, wider_score
    return best


def mark_size(stem: str, scale: float, width: int, height: int,
              directory: Path) -> tuple[float, float] | None:
    """The footprint `pattern_overlay` will give this mark, or None if unknown."""
    path = Path(directory) / f"{stem}.png"
    if not path.exists():
        return None
    try:
        import cv2

        art = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    except Exception:                                   # noqa: BLE001
        return None
    if art is None or not art.shape[0]:
        return None
    mark_w = max(1.0, scale * width)
    return mark_w, mark_w * art.shape[0] / max(art.shape[1], 1)


def _number(value: Any, rng: random.Random, default: float) -> float:
    """A rule may write a number or a `[low, high]` range. Both mean one number.

    Drawn here rather than in `pattern_overlay`, which takes floats and should
    keep taking floats: a range is a statement the RULES make about variety, and
    the model underneath has no business knowing about it.
    """
    if isinstance(value, (list, tuple)):
        if len(value) != 2:
            return default
        return rng.uniform(float(value[0]), float(value[1]))
    if isinstance(value, (int, float)):
        return float(value)
    return default


def marks_of(recipe) -> list[tuple[str, dict]]:
    """`[(stem, params)]` for this page, or `[]` for `no_ornament`."""
    drawn = recipe.get("ornament", "marks") or []
    out: list[tuple[str, dict]] = []
    for entry in drawn:
        if isinstance(entry, (list, tuple)) and entry:
            out.append((str(entry[0]),
                        dict(entry[1]) if len(entry) > 1 and entry[1] else {}))
        elif isinstance(entry, str):
            out.append((entry, {}))
    return out


def stamp(image, recipe, boxes: Sequence[dict], seed: int = 0):
    """Strike every mark this page's `ornament` asks for. Returns (image, report).

    Runs BEFORE the ageing chain, which is the order the rules are drawn in
    (`rules/_order.yaml`: ornament 6th, augmentation 7th) and the order the
    world works in -- a seal is struck on the paper, and then the paper is
    photocopied. Struck afterwards, a stamp on a screened photocopy would come
    out sharper than the text under it.

    Never resizes: the boxes measured from the DOM describe this image, and
    `render.py` asserts the shape is unchanged after the whole ageing step.
    """
    from degradation import apply_one

    # Which ornament VALUE this is, by id -- `seller_seal`, `qr_and_seal`. The
    # id lives on the Option, not in its params, so `recipe.get` (which reads
    # params) cannot see it and would have written an empty string on every page.
    option = recipe.choices.get("ornament")
    report = {"marks": [], "ornament": option.id if option else ""}
    drawn = marks_of(recipe)
    if not drawn:
        return image, report

    rng = random.Random(seed ^ 0x0072_6E6D)   # "orn": its own stream
    height, width = image.shape[:2]
    out = image
    for stem, params in drawn:
        name = str(params.get("anchor") or FALLBACK_ANCHOR)
        x0, y0, x1, y1, how = anchor(name, boxes, width, height)
        entry = {
            "pattern": stem,
            "anchor": name,
            "placed": how,
            "box": [round(x0), round(y0), round(x1), round(y1)],
        }
        if params.get("from_receipt"):
            # The rules ask for a barcode or a QR that encodes THIS receipt's
            # own number; what `textures/ornament/` holds is a sample of each.
            # Recorded rather than quietly ignored: the page is honest (nothing
            # labels the code), but a set whose barcodes do not decode to their
            # own invoices should say so where somebody will find it.
            entry["from_receipt"] = False
        scale = _number(params.get("scale"), rng, 0.26)
        # Move the mark off the text where the anchor leaves room for it.
        size = mark_size(stem, scale, width, height, ORNAMENT_DIR)
        if size is not None and boxes:
            placed = clearest((x0, y0, x1, y1), boxes, size,
                              page=(width, height))
            if placed is not None:
                x0, y0, x1, y1 = placed
                entry["box"] = [round(x0), round(y0), round(x1), round(y1)]
                entry["moved_off_text"] = True
        out = apply_one(out, "pattern_overlay", {
            "pattern": stem,
            "scale": scale,
            "opacity": _number(params.get("opacity"), rng, 0.8),
            "rotate": _number(params.get("rotate"), rng, 0.0),
            "box": (x0, y0, x1, y1),
        }, rng)
        report["marks"].append(entry)
    return out, report


def problems(rules=None) -> list[str]:
    """Every anchor a rule names that this file cannot resolve.

    Called by `pipeline/preflight.py`. An unknown anchor is not an error at
    render time -- the mark lands in the middle of the page instead -- which is
    exactly why it has to stop the run before the run starts.
    """
    from rulebase.spec import load_rules

    rules = rules or load_rules()
    found: list[str] = []
    for option in rules.get("ornament", []):
        for entry in option.params.get("marks") or []:
            params = entry[1] if isinstance(entry, (list, tuple)) and len(entry) > 1 else {}
            name = str((params or {}).get("anchor") or "")
            if name and name not in ANCHORS:
                found.append(
                    f"ornament/{option.id}: anchor {name!r} is not one of "
                    f"{', '.join(sorted(ANCHORS))}")
    return found


__all__ = ["ANCHORS", "FALLBACK_ANCHOR", "anchor", "marks_of", "problems", "stamp"]
